package tech.ajones.forcebuilder.model

val ajMiniNames = listOf(
  "Archer",
  "Atlas",
  "Awesome",
  "Axeman",
  "Banshee",
  "Battlemaster",
  "Blackjack",
  "Blackjack",
  "Black knight",
  "Bushwhacker",
  "Catapult",
  "Cataract",
  "Centurion",
  "Centurion",
  "Commando",
  "Conjurer",
  "Cyclops",
  "Dragon",
  "Enforcer",
  "Enforcer",
  "Exterminator",
  "Fire moth",
  "Gargoyle",
  "Grasshopper",
  "Griffin",
  "Hatchetman",
  "Highlander",
  "Horned owl",
  "Hunchback",
  "Ice Ferret",
  "Incubus",
  "Jenner",
  "King Crab",
  "Locust",
  "Locust",
  "Longbow",
  "Mad Dog",
  "Mercury",
  "Nightstar",
  "Nova",
  "Panther",
  "Phoenix Hawk",
  "Piranha",
  "Pouncer",
  "Raven",
  "Rifleman",
  "Sentinel",
  "Shadow Hawk",
  "Spider",
  "Stalker",
  "Thug",
  "Thunderbolt",
  "Timber Wolf",
  "Trebuchet",
  "Vapor Eagle",
  "Victor",
  "Viper",
  "Warhammer",
  "Warhammer IIC",
  "Warhawk",
  "Wasp",
  "Wolfhound",
  "Wolverine",
  "Wraith",
  "Zeus",
)

val tomasMiniNames = listOf(
  "Adder",
  "Archer",
  "Arctic Cheetah",
  "Atlas",
  "Battle Cobra",
  "Black Knight",
  "Black Lanner",
  "Blackjack",
  "Cataphract",
  "Centurion",
  "Conjurer",
  "Crossbow",
  "Dragon",
  "Ebon Jaguar",
  "Elemental Battle Armor",
  "Elemental Battle Armor",
  "Executioner",
  "Fire Falcon",
  "Fire Moth",
  "Lao Hu",
  "Hellion",
  "Horned Owl",
  "Howler",
  "Hunchback IIC",
  "Huntsman",
  "Incubus",
  "Kingfisher",
  "Kodiak",
  "Linebacker",
  "Locust",
  "Marauder IIC",
  "Mongrel",
  "Night Gyr",
  "Nova",
  "Nova",
  "Pack Hunter",
  "Phoenix Hawk",
  "Piranha",
  "Pouncer",
  "Rifleman",
  "Stone Rhino",
  "Supernova",
  "Timber Wolf",
  "Timber Wolf",
  "Turkina",
  "Vapor Eagle",
  "Warhammer",
  "Warhammer IIC",
  "Warhawk",
  "Wasp",
  "Wraith",
)